sudo: required

install:
  - curl -sSL https://get.docker.com/ | sudo sh

script:
  - sudo docker build -t frankgnl/sickrage-mp4-converter .
  - sudo docker run -d -p 8081:8081 frankgnl/sickrage-mp4-converter
  - sudo docker ps -a
