install:
  - curl -sSL https://get.docker.com/ | sudo sh

script:
  - sudo docker build -t sickrage:test .
  - sudo docker run -d -p 8081:8081 sickrage:test
  - sudo docker ps -a

notifications:
  email:
    recipients:
      - frank@groenewoud.me
    on_success: never
    on_failure: always
